### ISSUE TITLE
sound protocol integration checklist

### ISSUE THREAD

**Issue by TimDaub** [neume-network/data#64]
- [x] adjust https://github.com/neume-network/data/blob/9ce549f85c6b9c91637643ac82432271f050b8ec/steps/1.mjs#L43 to include both soundxyz and sound-protocol filtered contracts
- [x] update call-block-logs-transformation file
- [x] add sound-protocol step https://github.com/neume-network/data/blob/main/scripts/generateBlockLogsCrawlPath
- [x] add crawl steps for downloading tokenuri to the third step: https://github.com/neume-network/data/blob/main/steps/3.mjs, here is the config: https://github.com/neume-network/strategies/blob/57e4f2cf92f28307e7ed6d6a2c9d7ab810c82bf4/src/strategies/sound-protocol-call-tokenuri/extractor.mjs
- [x] add to checked-in files: https://github.com/neume-network/data/blob/main/.github/workflows/node.js.yml#L91
- [x] rebase with main branch to correct for #66 and re-run regular indexing job
- [x] define arweave gateway in environment variables
- [x] switch to strategies and core branch that fixes transformation issues
